import ast
import logging
import operator
import re
from typing import Any

from app.rag.retriever import retrieve_documents
from app.services.llm import generate_grounded_answer

logger = logging.getLogger(__name__)

ALLOWED_OPERATORS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.Pow: operator.pow,
    ast.USub: operator.neg,
}


def calculate(expression: str) -> float:
    """Safely calculate arithmetic without unrestricted eval."""
    tree = ast.parse(expression, mode="eval")
    return float(_eval_node(tree.body))


def percentage_growth(old_value: float, new_value: float) -> float:
    if old_value == 0:
        raise ValueError("Cannot calculate growth from a zero base value.")
    return calculate(f"({new_value} - {old_value}) / {old_value} * 100")


def _eval_node(node: ast.AST) -> float:
    if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
        return float(node.value)
    if isinstance(node, ast.BinOp) and type(node.op) in ALLOWED_OPERATORS:
        return ALLOWED_OPERATORS[type(node.op)](_eval_node(node.left), _eval_node(node.right))
    if isinstance(node, ast.UnaryOp) and type(node.op) in ALLOWED_OPERATORS:
        return ALLOWED_OPERATORS[type(node.op)](_eval_node(node.operand))
    raise ValueError("Unsupported calculator expression.")


def search_financial_documents(query: str, company: str | None = None) -> dict[str, Any]:
    search_query = f"{company} {query}" if company else query
    evidence = retrieve_documents(search_query)
    answer = generate_grounded_answer(query, evidence)
    return {"answer": answer, "sources": evidence}


def try_extract_revenue_growth(evidence: list[dict[str, Any]], start_year: int, end_year: int) -> dict[str, float] | None:
    """Best-effort extraction for simple demo questions about revenue growth."""
    values: dict[int, float] = {}
    for item in evidence:
        metadata = item["metadata"]
        year = metadata.get("year")
        text = item["text"].lower()
        if year not in {start_year, end_year} or "revenue" not in text and "net sales" not in text:
            continue
        numbers = re.findall(r"\$?\s?(\d{2,3}(?:,\d{3})+|\d{5,})", item["text"])
        if numbers:
            values[int(year)] = float(numbers[0].replace(",", ""))
    if start_year in values and end_year in values:
        return {
            "start_value": values[start_year],
            "end_value": values[end_year],
            "growth_percent": percentage_growth(values[start_year], values[end_year]),
        }
    return None


def explain_finance_concept(topic: str) -> str:
    concepts = {
        "free cash flow": "Free cash flow is cash generated by operations after capital expenditures. It helps show how much cash a company can use for debt repayment, dividends, buybacks, or reinvestment.",
        "ebitda": "EBITDA means earnings before interest, taxes, depreciation, and amortization. It is often used to compare operating performance before financing and accounting effects.",
        "working capital": "Working capital is current assets minus current liabilities. It measures short-term liquidity.",
        "gross margin": "Gross margin is revenue minus cost of goods sold, divided by revenue. It shows how much revenue remains after direct production costs.",
    }
    key = topic.lower().strip()
    return concepts.get(key, f"{topic} is a finance concept. For interview accuracy, add it to the local concept dictionary or answer it with an LLM provider.")


def parse_receipt_fields(text: str) -> dict[str, str | None]:
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    total_match = re.search(r"(total|amount due|balance)[^\d$]{0,12}(\$?\d+[.,]\d{2})", text, re.I)
    date_match = re.search(r"\b(\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|\d{4}[/-]\d{1,2}[/-]\d{1,2})\b", text)
    vendor = lines[0] if lines else None
    total = total_match.group(2) if total_match else None
    return {
        "vendor": vendor,
        "date": date_match.group(1) if date_match else None,
        "total": total,
        "currency": "$" if total and "$" in total else None,
        "category": "general expense",
    }
